package de.presti.ree6.logger.events;

// The used Log-Types.
public enum LogTyp {
    SERVER_JOIN, SERVER_LEAVE, SERVER_INVITE, VC_JOIN, VC_MOVE, VC_LEAVE, NICKNAME_CHANGE, ROLEDATA_CHANGE, MEMBERROLE_CHANGE, CHANNELDATA_CHANGE, USER_BAN, USER_UNBAN, MESSAGE_DELETE, ELSE
}