name: Create release

on:
  push:
    tags:
      - "*"
  workflow_dispatch: { }
permissions:
  contents: write

jobs:
  github:
    if: github.actor == 'DxsSucuk'
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set project version.
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dtag=${{ github.ref_name }} && mvn -B package --file Ree6-Installer/pom.xml
      - name: Copy Artifacts
        run: mkdir staging && cp target/*.jar staging && cp Ree6-Installer/target/*.jar staging
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          generateReleaseNotes: true
          artifacts: "staging/*.jar"
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ github.ref_name }}
